shouldSymlinkExtensionless: false
contentTypes: [json]
shouldDereference: false
schemaBasePath: ./schemas
skipSchemaTestCases:
  - description: "Skip schema test cases for frontmatter/document schema"
    matchPaths:
      - ./schemas/frontmatter/document/*.json
considerDeterministic:
  - oneOf
testCaseOverrides:
  "/frontmatter/document/1\\..*":
      # Ignore oneOf constraint in deterministic test
    - schema-deterministic-types:
        considerDeterministic:
          - oneOf
