shouldSymlinkExtensionless: false
contentTypes: [json]
shouldDereference: false
schemaVersionField: version
schemaBasePath: ./schemas
skipSchemaTestCases:
  ".*":
    - schema-snake-case-properties
testCaseOverrides:
  "/frontmatter/document/1\\..*":
      # Ignore oneOf constraint in deterministic test
    - schema-deterministic-types:
        considerDeterministic:
          - oneOf
          - anyOf
